### ISSUE TITLE
Escape sequence or special characters can break formspec

### ISSUE THREAD

**Issue by S-S-X** [pandorabox-io/priv_protector#4]
.. either clearing formspec or modifying it and can make formspec useless so protector cannot be removed / priv changed.
As priv is user input it should be sanitized properly for formspec.

There's some formspec escape function in mt api that should be easy fix.

edit. this: https://github.com/pandorabox-io/priv_protector/blob/4f0c2c11f55e7c36adb0b0b211cd0e9053aaf235/protector.lua#L10

**Comment by OgelGames** [comment]
A cleaner way to do this would be to use variable references: https://github.com/minetest/minetest/blob/d287da184cff737a661a78a2d485b6915316b28b/doc/lua_api.txt#L2380-L2382
```
* `default` is the default value of the field
    * `default` may contain variable references such as `${text}` which
      will fill the value from the metadata value `text`
```
Then the formspec wouldn't need to be updated every time the priv is changed.

**Comment by S-S-X** [comment]
> A cleaner way to do this would be to use variable references: https://github.com/minetest/minetest/blob/d287da184cff737a661a78a2d485b6915316b28b/doc/lua_api.txt#L2380-L2382
> 
> ```
> * `default` is the default value of the field
>     * `default` may contain variable references such as `${text}` which
>       will fill the value from the metadata value `text`
> ```
> 
> Then the formspec wouldn't need to be updated every time the priv is changed.

Actually I was now going to update that once more and tried that.

It does not fully work, can blame engine bug on this one. Well it works for most cases and it prevents form from breaking completely but write `interact\` to formspec and you'll have actually `interact\` as priv but `interact` displayed on formspec.
WIth `minetest.escape_formspec(priv)` you'll actually see `interact\` and backslash does not cut it.

`${priv}` does something different because `minetest.escape_formspec(priv)` actually seems to work (at least for all things I tested). It does not seem to correctly escape escape
